version: '3'

networks:
  sa:
    name: sa
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: dbmysql
    hostname: dbmysql 
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sa

  service:
    build: ./
    container_name: service
    hostname: service 
    restart: always 
    env_file:
      - .env 
    ports:
      - 80:3000
    networks:
      - sa